# Generated by Django 4.0.2 on 2022-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
