# Generated by Django 4.0.2 on 2022-04-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore_app', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
