# Generated by Django 4.0.2 on 2022-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore_app', '0004_book_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='url',
        ),
        migrations.AddField(
            model_name='navbar',
            name='path_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
