# Generated by Django 4.0.2 on 2022-04-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore_app', '0007_remove_cart_price_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
