# Generated by Django 4.0.2 on 2022-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore_app', '0008_remove_cartitem_book_remove_profile_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
