# Generated by Django 4.0.2 on 2022-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarystore_app', '0009_rename_title_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
